{
 "title": "Pull/Push",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Pull: Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (increase(service_total_count{job=\"dev-app\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Push: Total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (increase(service_total_count{job=\"app-service\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pull: Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_duration_milliseconds_bucket{job=\"dev-app\"}[5m])) by (instance,le))",
     "legendFormat": "95% {{instance}}"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(service_duration_milliseconds_bucket{job=\"dev-app\"}[5m])) by (instance,le))",
     "legendFormat": "90% {{instance}}"
    }
   ]
  },
  {
   "title": "Push: Percentile",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(service_duration_milliseconds_bucket{job=\"app-service\"}[5m])) by (instance,le))",
     "legendFormat": "95% {{instance}}"
    },
    {
     "expr": " histogram_quantile(0.90, sum(rate(service_duration_milliseconds_bucket{job=\"app-service\"}[5m])) by (instance,le))",
     "legendFormat": "90% {{instance}}"
    }
   ]
  },
  {
   "title": "Pull: Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_rows{job=\"dev-app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Push: Rows",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "service_rows{job=\"app-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}