{
 "title": "Load test",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Succesful reqs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_total_successful_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_total_failed_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    { "expr": "Loadtests_avg_latency_achieved", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests Overtime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "Loadtests_total_overall_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 11, "y": 9 },
   "targets": [
    { "expr": "Loadtests_current_rps" }
   ]
  },
  {
   "title": "Successful/failed reqs over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "Loadtests_total_successful_requests_made",
     "legendFormat": "__auto"
    },
    {
     "expr": "Loadtests_total_failed_requests_made",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}