{
 "title": "RHTAP Load test",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(Loadtests_loadtest_successful_application_creations,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Successful User Creations Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_loadtest_successful_user_creations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Application Creations",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_loadtest_successful_application_creations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful Components Created",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_loadtest_successful_component_creations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pipeline Runs Created Successfully",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_loadtest_successful_pipelineruns_creations{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entities created successfully",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_user_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "users"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_application_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "applications"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_CDQ_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "cdqs"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_component_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "components"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_pipelineruns_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "pipeline runs"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_IntegrationPipelineRuns_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "integration pipeline runs"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_IntegrationTestSenario_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "integration test scenarios"
    },
    {
     "expr": "sum(rate(Loadtests_loadtest_successful_deployments_creations{job=\"$job\"}[$__rate_interval]))",
     "legendFormat": "deployments"
    }
   ]
  },
  {
   "title": "Pipeline Run Time",
   "type": "timeseries",
   "description": "Completed Time subtracted with creation time ",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 8 },
   "targets": [
    {
     "expr": "Loadtests_loadtest_pipelinerun_time{job=\"$job\"}",
     "legendFormat": "PipelineRun duration"
    }
   ]
  }
 ]
}